description: This is the baseline line detector.
constructor: line_detector.LineDetectorHSV
parameters:
    configuration:
      dilation_kernel_size: 3
      canny_thresholds: [80, 200]

      hough_threshold: 2
      hough_min_line_length: 3
      hough_max_line_gap: 1

      hsv_white1:  [0,0,150]
      hsv_white2:  [180,60,255]
      hsv_yellow1: [25,140,100]
      hsv_yellow2: [45,255,255]
      hsv_red1:    [0,140,100]
      hsv_red2:    [15,255,255]
      hsv_red3:    [165,140,100]
      hsv_red4:    [180,255,255]
      hsv_green1:  [45, 100, 100]
      hsv_green2:  [75, 255, 255]
      hsv_blue1:    [110, 100, 100]
      hsv_blue2:    [130, 255, 255]
